Update FloorPlanActivity.java
Veldhuis94/OPEN-DAY-APP pull request #37
Opened 2019-05-17 13:43 UTC by Veldhuis94

- Greyed out the buttons if the floor above or below respectively, is unavailable
- Changed color of building button that is currently selected
- Added the fact that the buttons are disabled when they cannot be pressed
- Auto-cleanup code (switch to Java-style array declarations, removed redundant type declarations)

2019-05-18 20:09 UTC, avgog requested changes
Found a bug. If you are on the fifth floor of WN and switch to WD or H building, the plus button
won't be enabled. It should be, because there is a sixth floor in the WD and H buildings.

2019-05-19 14:42 UTC, Mohamed1651 reviewed
You might want to change the if statements in floorCheck() to elif statements.

2019-05-19 15:07 UTC, avgog approved these changes
Bug has been fixed. The buttons work properly now. Approved!

2019-05-20 09:45 UTC, Veldhuis94 commented
> You might want to change the if statements in floorCheck() to elif statements.

elif does not exist in Java mate

2019-05-20 10:47 UTC, HakanDalama approved these changes
tested it and it works

2019-05-21 09:15 UTC, LucasOudhuis approved these changes
All works for me

2019-05-21 09:15 UTC, merged