Translated necessary strings (Open day detail page and main screen)
Veldhuis94/OPEN-DAY-APP pull request #52
Opened 2019-06-02 20:53 UTC by Veldhuis94

2019-06-03 11:04 UTC, HakanDalama approved these changes
it is correctly translated

2019-06-03 19:19 UTC, avgog requested changes
You weren't supposed to remove the %s of OpenDay_Test1 and 2. It's used for string formatting to display
the full dates. That is especially handy when loading the dates from the database.
Replace the dates you've filled in with %s' if you want this pull request to be approved.

2019-06-04 18:12 UTC, LucasOudhuis approved these changes

2019-06-04 18:41 UTC, avgog approved these changes
The dates are now right.

2019-06-04 18:42 UTC, merged