Questionnaire
Veldhuis94/OPEN-DAY-APP pull request #55
Opened 2019-06-03 11:22 UTC by Veldhuis94

Questionnaire POC,, usable for other tasks!!

2019-06-03 17:06 UTC, avgog requested changes
Requested changes:
-Toolbar is empty (no text and sidebar button) and it has the wrong color.
-You can submit your score even tough you haven't done all the questions, that shouldn't happen.

Recommended changes:
Those are changes that I would like to be implemented, but I understand that you can't implement
these changes on time during the limited amount of time left of this sprint, so I consider them now
as recommended changes.
-Add comments to your code.
-Create actual questions and choices of a study course instead of leaving them like "Question 1", "Option 1", etc. You can decide the study course but you need to change their content. This is handy for
the user tests.
-The questions, values and amount of points needs to be loaded from strings.xml for translation and
being able to add questions without writing seperate code. That also means that the amount of questions and choices are dynamic. (You can also do this with a database, but that's quite hard
to implement.)
-Show the score as a percentage value.

Other: 
-I would like that you support night mode, but that isn't possible yet because my branch hasn't been
merged with the master yet. If you are going to do that later, I suggest you look to the other
layouts that support night mode. Ask me for help if needed.
and choices

2019-06-04 17:07 UTC, agrida2 approved these changes

2019-06-04 18:07 UTC, HakanDalama approved these changes

2019-06-04 18:10 UTC, LucasOudhuis approved these changes

2019-06-04 18:19 UTC, avgog approved these changes
The toolbar works and it's being displayed the right way and you aren't able to submit without
choicing the answer of every question anymore. Approved.

2019-06-04 18:19 UTC, merged