Questionnaire2
Veldhuis94/OPEN-DAY-APP pull request #74
Opened 2019-06-15 16:04 UTC by Mohamed1651

2019-06-15 20:19 UTC, Dinesh0966028 requested changes
everything just works well. There are a number of problems.
1. Not all questions are translated.
2. The first two questions you call "statements" and the last one you call "question".
3. The night mode does not work on questionaire page man bro.

2019-06-16 16:58 UTC, VeeNinetyFour approved these changes
Everything's good. Night mode is not that important.

2019-06-16 18:01 UTC, avgog requested changes
Change the toolbar text to "Questionnaire" or "Result", than I'll approve it.

2019-06-16 18:25 UTC, avgog approved these changes

2019-06-16 18:33 UTC, closed without merging