MULTIPAGE SYSTEM IN PLACE
Veldhuis94/OPEN-DAY-APP pull request #8
Opened 2019-04-23 13:43 UTC by Veldhuis94

A system where one activity can be used to display different pages, in this case to be used in the Study Program Detail pages.

When the time is right, the buttons will be moved to their intended locations.

Co-Authored-By: avgog <avgog@users.noreply.github.com>

2019-04-24 09:41 UTC, LucasOudhuis submitted a review, later dismissed
Wel goed denk ik

2019-04-24 12:02 UTC, avgog requested changes
1. verplaats de temp knoppen naar boven (net onder de lijst met open dagen), ik heb geen zin om elke keer naar beneden te scrollen.
2. Het is niet echt verstandig om voor elk opleidingpagina aparte code te schrijven om de tekst aan de hand van de page id aan te passen. Ik raad je aan om een list of een array te gebruiken.

2019-04-24 18:23 UTC, avgog approved these changes
Goed dat je nu string arrays gebruikt voor de opleidinggegevens. Misschien kun je comments aan je code toevoegen zodat anderen het makkelijker kunnen begrijpen, maar omdat ik al tevreden ben met je veranderingen approve ik dit.

2019-04-25 10:21 UTC, agrida2 reviewed
Don't see any conflicts! GoogleAppindexingWarning is something new

2019-04-25 10:53 UTC, agrida2 approved these changes
The strings in java is a nice way of changing the webpage!

2019-04-25 11:08 UTC, LucasOudhuis approved these changes
Looks good

2019-04-25 11:08 UTC, merged